Introduce `Error` and `Result` types for crates
We are reaching a state of maturity where we can start to introduce
`Error` and `Result` types for crates. This is a first step towards
making the error handling in crates more consistent and easier to
understand.

For library crates, I propose to use `thiserror` to define custom
`Error` types. This is because downstream users can then use these
types to match on specific errors.

For user-facing crates (such as the axum server), we can keep using `anyhow`.

Example error message from axum after the refactoring:

```sh
Error: AppError(Failed to load settings from env

Caused by:
    0: config error: env lookup error
    1: env lookup error
    2: error looking key 'AWS_ACCESS_KEY_ID' up: environment variable not found
    3: environment variable not found)
```

It gives us a bit more context as what happened.
Still not perfect, but a step into the right direction, I guess.
In general, the errors should help us pin down what went wrong and where.

Where possible, I fixed the tests as well. Some of them transitioned to `async/await`,
so `tokio` as a dependency was enabled again for those crates.

Further changes

- Formatted code with `cargo fmt`
- Applied `clippy` suggestions

Please test thoroughly before merging.